#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
IDF_PATH = $(PWD)/../libs/esp-idf

PROJECT_NAME = hello_world

include $(IDF_PATH)/make/project.mk
