#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

IDF_PATH     := $(PWD)/../libs/esp-idf
PROJECT_NAME := http-request

include $(IDF_PATH)/make/project.mk

CFLAGS   += -std=gnu11
CXXFLAGS += -std=gnu++17
